### ISSUE TITLE
Download fails with HTTP 403, but other applications succeed

### ISSUE THREAD

**Issue by magneticflux-** [aria2/aria2#1932]
Running this command:
```
aria2c https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
```
fails after redirecting with an HTTP 403 error. Setting the User Agent to Firefox and limiting concurrent downloads to 1 (`--user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0' -j 1`) does not fix it.

Both `curl` and `wget` successfully download the file.

Here are the logs from my download:
```
aria2c -l - https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip --user-agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0' -j 1
2022-05-28 18:58:16.575654 [INFO] [Context.cc:179] <<--- --- --- ---
2022-05-28 18:58:16.575654 [INFO] [Context.cc:180]   --- --- --- ---
2022-05-28 18:58:16.575654 [INFO] [Context.cc:181]   --- --- --- --->>
2022-05-28 18:58:16.576158 [INFO] [Context.cc:182] aria2 1.36.0
2022-05-28 18:58:16.576158 [INFO] [Context.cc:183] mingw-w64 8.0.0 (alpha) / gcc 10-win32 20210110
  built by  x86_64-pc-linux-gnu
  targeting x86_64-w64-mingw32
  on        Aug 21 2021 17:37:16
2022-05-28 18:58:16.576158 [INFO] [Context.cc:184] Windows 6.2 (x86_64) (6.2)
2022-05-28 18:58:16.576662 [INFO] [Context.cc:185] zlib/1.2.11 expat/2.4.1 sqlite3/3.36.0 GMP/6.2.1 c-ares/1.17.2 libssh2/1.9.0
2022-05-28 18:58:16.576662 [INFO] [Context.cc:186] Logging started.
2022-05-28 18:58:16.576662 [INFO] [SocketCore.cc:1585] Checking configured addresses
2022-05-28 18:58:16.581200 [INFO] [SocketCore.cc:1649] Not considered: fe80::2951:1a67:cc2c:e382%25
2022-05-28 18:58:16.581704 [INFO] [SocketCore.cc:1646] Found configured address: 10.0.1.55
2022-05-28 18:58:16.581704 [INFO] [SocketCore.cc:1649] Not considered: fe80::5596:ed13:b8a6:44e2%19
2022-05-28 18:58:16.581704 [INFO] [SocketCore.cc:1649] Not considered: 169.254.68.226
2022-05-28 18:58:16.581704 [INFO] [SocketCore.cc:1649] Not considered: fe80::3db8:e551:a5b1:ba3e%4
2022-05-28 18:58:16.582208 [INFO] [SocketCore.cc:1649] Not considered: 169.254.186.62
2022-05-28 18:58:16.582208 [INFO] [SocketCore.cc:1649] Not considered: fe80::872:1873:b7eb:7da5%12
2022-05-28 18:58:16.582208 [INFO] [SocketCore.cc:1649] Not considered: 169.254.125.165
2022-05-28 18:58:16.582208 [INFO] [SocketCore.cc:1649] Not considered: fe80::9160:e774:5973:233f%13
2022-05-28 18:58:16.582712 [INFO] [SocketCore.cc:1646] Found configured address: 192.168.198.1
2022-05-28 18:58:16.582712 [INFO] [SocketCore.cc:1649] Not considered: fe80::c887:f57a:6dee:6f02%16
2022-05-28 18:58:16.582712 [INFO] [SocketCore.cc:1646] Found configured address: 192.168.171.1
2022-05-28 18:58:16.582712 [INFO] [SocketCore.cc:1649] Not considered: fe80::a09d:16ca:91fc:f976%2
2022-05-28 18:58:16.583217 [INFO] [SocketCore.cc:1649] Not considered: 169.254.249.118
2022-05-28 18:58:16.583217 [INFO] [SocketCore.cc:1649] Not considered: ::1
2022-05-28 18:58:16.583217 [INFO] [SocketCore.cc:1649] Not considered: 127.0.0.1
2022-05-28 18:58:16.583217 [INFO] [SocketCore.cc:1649] Not considered: fe80::89a3:9bb8:1783:c400%28
2022-05-28 18:58:16.583217 [INFO] [SocketCore.cc:1646] Found configured address: 172.30.128.1
2022-05-28 18:58:16.583721 [INFO] [SocketCore.cc:1649] Not considered: fe80::40df:6de1:6db:face%49
2022-05-28 18:58:16.583721 [INFO] [SocketCore.cc:1646] Found configured address: 172.26.0.1
2022-05-28 18:58:16.583721 [INFO] [SocketCore.cc:1656] IPv4 configured=1, IPv6 configured=0
2022-05-28 18:58:16.583721 [NOTICE] [Context.cc:310] Downloading 1 item(s)

05/28 18:58:16 [NOTICE] Downloading 1 item(s)
2022-05-28 18:58:16.584730 [DEBUG] [RequestGroupMan.cc:591] 1 RequestGroup(s) added.
2022-05-28 18:58:16.585236 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.585236 [DEBUG] [FeedbackURISelector.cc:162] Selected from normCands
2022-05-28 18:58:16.585236 [DEBUG] [FeedbackURISelector.cc:84] FeedbackURISelector selected https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
2022-05-28 18:58:16.585741 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.590322 [INFO] [AsyncNameResolverMan.cc:82] CUID#7 - Resolving hostname www.sumatrapdfreader.org
2022-05-28 18:58:16.609456 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.609456 [INFO] [AbstractCommand.cc:816] CUID#7 - Name resolution complete: www.sumatrapdfreader.org -> 104.26.9.244, 104.26.8.244, 172.67.68.92
2022-05-28 18:58:16.609959 [INFO] [HttpInitiateConnectionCommand.cc:123] CUID#7 - Connecting to 104.26.9.244:443
2022-05-28 18:58:16.610462 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.626653 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:1, hup:0, err:0
2022-05-28 18:58:16.626653 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:1, hup:0, err:0
2022-05-28 18:58:16.626653 [DEBUG] [SocketCore.cc:926] Creating TLS session
2022-05-28 18:58:16.628163 [DEBUG] [SocketCore.cc:946] TLS Handshaking
2022-05-28 18:58:16.628163 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2022-05-28 18:58:16.628163 [DEBUG] [WinTLSSession.cc:604] WinTLS: Initializing handshake
2022-05-28 18:58:16.628666 [DEBUG] [WinTLSSession.cc:630] WinTLS: Writing handshake
2022-05-28 18:58:16.628666 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2022-05-28 18:58:16.660071 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:1, write:0, hup:0, err:0
2022-05-28 18:58:16.660071 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2022-05-28 18:58:16.660071 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2022-05-28 18:58:16.662107 [DEBUG] [WinTLSSession.cc:758] WinTLS: Continuing with handshake
2022-05-28 18:58:16.662107 [DEBUG] [WinTLSSession.cc:630] WinTLS: Writing handshake
2022-05-28 18:58:16.662107 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2022-05-28 18:58:16.682119 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:1, write:0, hup:0, err:0
2022-05-28 18:58:16.682119 [DEBUG] [WinTLSSession.cc:585] WinTLS: Starting/Resuming TLS Connect
2022-05-28 18:58:16.682119 [DEBUG] [WinTLSSession.cc:662] WinTLS: Reading handshake...
2022-05-28 18:58:16.684121 [INFO] [WinTLSSession.cc:788] WinTLS: connected with: TLS_RSA_WITH_AES_128_CBC_SHA
2022-05-28 18:58:16.684121 [DEBUG] [SocketCore.cc:993] Securely connected to www.sumatrapdfreader.org (104.26.9.244:443) with TLSv1.2
2022-05-28 18:58:16.684121 [INFO] [HttpConnection.cc:128] CUID#7 - Requesting:
GET /dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Accept: */*,application/metalink4+xml,application/metalink+xml
Host: www.sumatrapdfreader.org
Want-Digest: SHA-512;q=1, SHA-256;q=1, SHA;q=0.1


2022-05-28 18:58:16.684121 [DEBUG] [WinTLSSession.cc:336] WinTLS: Write request: 294 buffered: 0
2022-05-28 18:58:16.684121 [DEBUG] [WinTLSSession.cc:279] WinTLS: TLS record 0 bytes left
2022-05-28 18:58:16.684121 [DEBUG] [WinTLSSession.cc:404] WinTLS: Write TLS record header: 21 body: 294 trailer: 26
2022-05-28 18:58:16.685120 [DEBUG] [WinTLSSession.cc:279] WinTLS: TLS record 341 bytes left
2022-05-28 18:58:16.685120 [DEBUG] [WinTLSSession.cc:428] WinTLS: Write result: 294
2022-05-28 18:58:16.830585 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:1, write:0, hup:0, err:0
2022-05-28 18:58:16.831576 [DEBUG] [WinTLSSession.cc:435] WinTLS: Read request: 16384 buffered: 0
2022-05-28 18:58:16.831576 [INFO] [HttpConnection.cc:163] CUID#7 - Response received:
HTTP/1.1 307 Temporary Redirect
Date: Sat, 28 May 2022 23:58:06 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Location: https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip
Vary: Accept-Encoding
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
CF-Cache-Status: BYPASS
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=h3qrD9JcFNrnjICXjWHPToANPZ7vx9fptt8ETH0%2BYFRwoNObe22zNj68r0gwvihBQ6DcRQIYtbwMtKqv%2FK7%2F3JM6RgU0Ju0hVRfxfPACydN%2BN05JP46SXOiAOdWM%2BzJmC3ZALnY%2BteUVkQ%3D%3D"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 712aefb9087161b6-ORD


2022-05-28 18:58:16.832576 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.832576 [INFO] [DownloadEngine.cc:315] Pool socket for 104.26.9.244(443)
2022-05-28 18:58:16.832576 [NOTICE] [HttpResponse.cc:168] CUID#7 - Redirecting to https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip

05/28 18:58:16 [NOTICE] CUID#7 - Redirecting to https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip
2022-05-28 18:58:16.832576 [DEBUG] [AbstractCommand.cc:451] CUID#7 - Pooling request URI=https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
2022-05-28 18:58:16.833578 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.833578 [DEBUG] [FileEntry.cc:225] Picked up from pool: https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
2022-05-28 18:58:16.833578 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.837579 [INFO] [AsyncNameResolverMan.cc:82] CUID#7 - Resolving hostname files.sumatrapdfreader.org
2022-05-28 18:58:16.874804 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.875796 [INFO] [AbstractCommand.cc:816] CUID#7 - Name resolution complete: files.sumatrapdfreader.org -> 104.26.9.244, 172.67.68.92, 104.26.8.244
2022-05-28 18:58:16.875796 [INFO] [DownloadEngine.cc:449] Found socket for 104.26.9.244(443)
2022-05-28 18:58:16.875796 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:1, hup:0, err:0
2022-05-28 18:58:16.875796 [INFO] [HttpConnection.cc:128] CUID#7 - Requesting:
GET /file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip HTTP/1.1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Accept: */*,application/metalink4+xml,application/metalink+xml
Host: files.sumatrapdfreader.org
Want-Digest: SHA-512;q=1, SHA-256;q=1, SHA;q=0.1


2022-05-28 18:58:16.876796 [DEBUG] [WinTLSSession.cc:336] WinTLS: Write request: 328 buffered: 0
2022-05-28 18:58:16.876796 [DEBUG] [WinTLSSession.cc:279] WinTLS: TLS record 0 bytes left
2022-05-28 18:58:16.876796 [DEBUG] [WinTLSSession.cc:404] WinTLS: Write TLS record header: 21 body: 328 trailer: 24
2022-05-28 18:58:16.876796 [DEBUG] [WinTLSSession.cc:279] WinTLS: TLS record 373 bytes left
2022-05-28 18:58:16.876796 [DEBUG] [WinTLSSession.cc:428] WinTLS: Write result: 328
2022-05-28 18:58:16.896522 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:1, write:0, hup:0, err:0
2022-05-28 18:58:16.896522 [DEBUG] [WinTLSSession.cc:435] WinTLS: Read request: 16384 buffered: 0
2022-05-28 18:58:16.896522 [INFO] [HttpConnection.cc:163] CUID#7 - Response received:
HTTP/1.1 403 Forbidden
Server: cloudflare
Date: Sat, 28 May 2022 23:58:06 GMT
Content-Type: text/html
Content-Length: 151
Connection: keep-alive
CF-RAY: 712aefba39f161b6-ORD


2022-05-28 18:58:16.897515 [DEBUG] [AbstractCommand.cc:181] CUID#7 - socket: read:0, write:0, hup:0, err:0
2022-05-28 18:58:16.897515 [INFO] [DownloadEngine.cc:315] Pool socket for 104.26.9.244(443)
2022-05-28 18:58:16.897515 [ERROR] [AbstractCommand.cc:349] CUID#7 - Download aborted. URI=https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403

05/28 18:58:16 [ERROR] CUID#7 - Download aborted. URI=https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://files.sumatrapdfreader.org/file/kjk-files/software/sumatrapdf/rel/3.4.2/SumatraPDF-3.4.2-64.zip
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
2022-05-28 18:58:16.898515 [DEBUG] [AbstractCommand.cc:479] CUID#7 - Aborting download
2022-05-28 18:58:16.898515 [DEBUG] [AbstractCommand.cc:423] CUID#7 - Not trying next request. No reserved/pooled request is remaining and total length is still unknown.
2022-05-28 18:58:16.898515 [DEBUG] [RequestGroup.cc:983] GID#0ff827e1950b81a6 - Request queue check
2022-05-28 18:58:16.898515 [NOTICE] [RequestGroupMan.cc:424] Download GID#0ff827e1950b81a6 not complete:

05/28 18:58:16 [NOTICE] Download GID#0ff827e1950b81a6 not complete:
2022-05-28 18:58:16.898515 [DEBUG] [RequestGroup.cc:1173] GID#0ff827e1950b81a6 - Creating DownloadResult.
2022-05-28 18:58:16.898515 [DEBUG] [RequestGroupMan.cc:481] 1 RequestGroup(s) deleted.

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
0ff827|ERR |       0B/s|https://www.sumatrapdfreader.org/dl/rel/3.4.2/SumatraPDF-3.4.2-64.zip

Status Legend:
(ERR):error occurred.

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
2022-05-28 18:58:16.899515 [DEBUG] [WinTLSSession.cc:181] WinTLS: Closing connection
2022-05-28 18:58:16.900515 [DEBUG] [WinTLSSession.cc:336] WinTLS: Write request: 53 buffered: 0
2022-05-28 18:58:16.900515 [DEBUG] [WinTLSSession.cc:279] WinTLS: TLS record 0 bytes left
2022-05-28 18:58:16.900515 [DEBUG] [WinTLSSession.cc:397] WinTLS: Failed to encrypt a message! Error: The context has expired and can no longer be used.
(80090317)
2022-05-28 18:58:16.900515 [DEBUG] [WinTLSSession.cc:225] WinTLS: Closed Connection
```

**Comment by magneticflux-** [comment]
That does not change the download error. I also experimented with putting different versions in, but that didn't help either.

**Comment by jaum20** [comment]
Any update on this? I have the same problem

**Comment by xrgzs** [comment]
Same problem:

- 30x redirect
- **Cross-Origin** request after 30x redirected
- Both domains are on **Cloudflare CDN**
- aria2c failed with errorCode=22, status=403
- `curl -l` works well

There is no problem with downloading the **redirected link** directly using aria2.

I used [Requable](https://github.com/Reqable/reqable-app) proxy capture tool to get more details about the HTTP headers. Both domains were connected to the same IP. But I couldn't reproduce the problem under the proxy. 

Then I looked at the error log (`--console-log-level=debug`) without proxy. There was a line before the error 403:

```shell
[INFO] Pool socket for 172.66.44.79(443)

[NOTICE] CUID#7 - Redirecting to ***

[INFO] Found socket for 172.66.44.79(443)
```

I assigned **2 different IPs** of Cloudflare CDN to 2 domains in Hosts, and the problem was solved.

```txt
172.66.44.79 www.example.com
172.66.44.80 files.example.com
```

So the problem may be related to the reuse of the same socket connection in aria2's socket pool. This explains why manually specifying different IPs for different domains can solve this problem.

**Comment by kayu5h** [comment]
Thanks for the explanation and for retesting the links. That's interesting that it worked for you. However, I've just tried the download again, and I'm still encountering the 403 Forbidden error. I guess there's something else at play for my connection. The server at files.modyolo.com (which is Cloudflare's edge in this case) received aria2's request but explicitly denied it with a 403 status. Cloudflare's bot detection/security measures might be actively blocking my aria2 request. 

I also tried `--user-agent=firefox` and `--user-agent=chrome`, still the same error. 

I have also tried `aria2c --referer="https://modyolo.com/download/adobe-acrobat-248187/" https://files.modyolo.com/Adobe%20Acrobat%20Reader/Adobe_Acrobat_25.4.1.38544.apk`
but still ended up with the same error. Am I missing something or is there a regional blocking system used by Cloudflare here?
